name: Publish Podspec Main

# on:
#   release:
#     types: [published]
on: 
  workflow_dispatch:
    inputs:
      tag:
        description: 'tag/version'     
        required: true
        default: '1.0.0'

jobs:
  build:

    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch  
#     - name: Install Cocoapods
#       run: gem install cocoapods
      
#     - name: Deploy to Cocoapods
#       run: |
#         pod lib lint --allow-warnings  
