name: Publish Podspec


on: 
  workflow_dispatch:
    inputs:
      tag:
        description: 'tag/version'     
        required: true
        default: '1.0.0'

jobs:
  build:

    runs-on: macos-latest
    
    steps:
      
    - name: Build Changelog
      id: github_release
      uses: mikepenz/release-changelog-builder-action@main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: echo
      run: echo release notes ${{steps.github_release.outputs.changelog}}
#     - name: Install Cocoapods
#       run: gem install cocoapods
      
#     - name: Deploy to Cocoapods
#       run: |
#         pod lib lint --allow-warnings  
