name: Publish Podspec


on: 
  workflow_dispatch:
    inputs:
      tag:
        description: 'tag/version'     
        required: true
        default: '1.0.0'

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      # Drafts your next Release notes as Pull Requests are merged into "master"
    - uses: release-drafter/release-drafter@v5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

# jobs:
#   build:

#     runs-on: macos-latest
    
#     steps:
#     - uses: actions/checkout@v2
#       with:
#         ref: main
#     - name: Build Changelog
#       id: github_release
#       uses: mikepenz/release-changelog-builder-action@main
#       env:
#         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#     - name: echo
#       run: echo release notes ${{steps.github_release.outputs.changelog}}
#     - name: Install Cocoapods
#       run: gem install cocoapods
      
#     - name: Deploy to Cocoapods
#       run: |
#         pod lib lint --allow-warnings  
