name: Release


on: 
  workflow_dispatch:
    inputs:
      tag:
        description: 'tag/version'     
        required: true
        default: '0.0.2'

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
    - uses: release-drafter/release-drafter@v5
      with:
        name: v${{ github.event.inputs.logLevel }}
        tag: ${{ github.event.inputs.logLevel }}
        version: ${{ github.event.inputs.logLevel }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
