name: Release


on: 
  workflow_dispatch:
    inputs:
      tag:
        description: 'tag/version'     
        required: true
        default: '1.0.0'

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
    - uses: release-drafter/release-drafter@v5
      with:
        name: v0.0.1
        tag: 0.0.1
        version: 0.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
