name: Release


on: 
  workflow_dispatch:
    inputs:
      tag:
        description: 'tag/version'     
        required: true
        default: '0.0.2'

jobs:
  update_release_draft:
    runs-on: macos-latest
    steps:
    # "release-drafter" action docs -> https://github.com/marketplace/actions/release-drafter
    - uses: release-drafter/release-drafter@v5
      with:
        name: v${{ github.event.inputs.tag }}
        tag: ${{ github.event.inputs.tag }}
        version: ${{ github.event.inputs.tag }}
        publish: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - uses: actions/checkout@v2
      with:
        ref: main
    - name: Publicsh Pods
      run: |
        gem install cocoapods
        pod lib lint --allow-warnings
        
        
